# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# ワークフローの表示名
name: 1weekPDCA_CI

# ワークフローの起動条件を定義する
on:

  # プルリクエストが作成 or 更新された時
  pull_request:
    types:
      - opened
      - synchronize
      
  # main or develop or feature~ ブランチに push された時
  push:
    branches:
      - main
      - develop
      - feature/**
      
  workflow_dispatch:

# 複数のジョブを定義する
# 各ジョブはそれぞれまったく別々の環境で実行される

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2

      - name: Test
        run: xcodebuild test -project 1weekPDCA.xcodeproj/ -scheme 1weekPDCA -resultBundlePath TestResults -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14"
        
        
      - uses: kishikawakatsumi/xcresulttool@v1.7.0
        with:
          path: TestResults.xcresult
        if: success() || failure()
