# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# ワークフローの表示名
name: 1weekPDCA_CI

# ワークフローの起動条件を定義する
on:

  # プルリクエストが作成 or 更新された時
  pull_request:
    types:
      - opened
      - synchronize
      
  # main or develop or feature~ ブランチに push された時
  push:
    branches:
      - main
      - develop
      - feature/**

# 複数のジョブを定義する
# 各ジョブはそれぞれまったく別々の環境で実行される

jobs:
  build:
    name: Build and Test default scheme using iPhone
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Force Xcode 14
        run: sudo xcode-select -switch /Applications/Xcode_14.2.app
      - name: iOS test
        run: >-
          xcodebuild test -workspace 1weekPDCA.xcworkspace-scheme 1weekPDCA

