# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

# ワークフローの表示名
name: 1weekPDCA_CI

# ワークフローの起動条件を定義する
on:

  # プルリクエストが作成 or 更新された時
  pull_request:
    types:
      - opened
      - synchronize
      
  # main or develop ブランチに push された時
  push:
    branches:
      - main
      - develop

# 複数のジョブを定義する
# 各ジョブはそれぞれまったく別々の環境で実行される
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Swift
      uses: actions/setup-swift@v2
      with:
        swift-version: '5.5'

    - name: Build
      run: swift build

    - name: Test
      run: swift test
